export const FETCH_DATA = '@CLASSIC/FETCH_DATA';
export const FETCH_DATA_REJECTED = '@CLASSIC/FETCH_DATA_REJECTED';
export const EXTRACT_WINNERS = '@CLASSIC/EXTRACT_WINNERS';
export const DATA_FETCHED = '@CLASSIC/DATA_FETCHED';
