export const FETCH_DATA = '@GWOVERALL/FETCH_DATA';
export const FETCH_DATA_REJECTED = '@GWOVERALL/FETCH_DATA_REJECTED';
export const DATA_FETCHED = '@GWOVERALL/DATA_FETCHED';
export const SELECT_OPTION = '@GWOVERALL/SELECT_OPTION';
